### ISSUE TITLE
[bug] configuration expect for sizing wouldn't be reverted back when the commonservice CR is deleted

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-common-service-operator#366]
Steps to reproduce:

Create CR:
```
apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  name: common-service
spec:
  services:
  - name: ibm-mongodb-operator
    spec:
      mongoDB:
        storageClass: rook-cephfs
``` 

The `storageClass: rook-cephfs` is added in `OperandConfig`.

Delete the CR:

The storageclass still there.

We expect the storageclass will be removed from the  `OperandConfig`.
