### ISSUE TITLE
As a Cloud Pak I want to request a CommonService CR through an operandrequest 

### ISSUE THREAD

**Issue by taylormgeorge91** [IBM/ibm-common-service-operator#491]
## Details

As a Cloud Pak that has adopted the use of ODLM to manage its resources, I want to configure and deploy a *local* CommonService CR to be reconciled with the base resource (resides in `ibm-common-services` namespace by default).

The Cloud Pak has a Lead operator and a handful of Component operators. There is no Capability operator layer at this time.
As such, the Lead operator could be thought of also as a capability operator itself. In order to provide a design that allows for seamless transition between the various Lead and Capability topologies and entry points, we would like to utilize ODLM to manage the request for the local `CommonService` resource. 

@gyliu513 @horis233

**Comment by Daniel-Fan** [comment]
If we add the `ibm-common-service-operator` into the `common-service` `OperandRegistry`, we could actually create the CommonService CR by`OperandRequest` through this new feature.
https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/docs/design/create-cr-by-operandrequest.md

The below example will create the CommonService CR in `cloud-pak1` namespace,
```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: CS-instance
  namespace: cloud-pak1
spec:
  requests:
  - registry: common-service
    registryNamespace: ibm-common-services
    operands:
    - name: ibm-common-service-operator
      kind: CommonService
      apiVersion: operator.ibm.com/v3
      instanceName: common-service
      spec:
        size: small
```

@horis233 Please correct me if I am wrong.
